#ifndef STATGHOST_RESOURCE_H
#define STATGHOST_RESOURCE_H

#ifndef IDC_STATIC
#define IDC_STATIC -1
#endif

#define IDD_STATGHOST_PANEL 2600
#define IDD_STATGHOST_CONFIG 2601

#define IDC_HOST_EXE 2101
#define IDC_HOST_BROWSE 2102
#define IDC_CHROME_LIST 2103

#endif
